# Generated by Django 5.0.9 on 2024-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('numero_leitor', models.IntegerField(db_column='NumeroLeitor', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('apelido', models.CharField(db_column='Apelido', max_length=255)),
            ],
            options={
                'db_table': 'Leitor',
                'managed': False,
            },
        ),
    ]
